### ISSUE TITLE
Broken formatting with new python.el (0.28)

### ISSUE THREAD

**Issue by timlod** [glyph/python-docstring-mode#30]
Since the new update to the built-in python mode, `python-docstring-fill`does not work fully anymore.

The following code will not change when formatted with `python-docstring-fill`, python.el version 0.27.1:
```python
def fun(a):
    """
    Do something.

    :param a: do something with a
    """
```

When using python.el, version 0.28, `python-docstring-fill`will now format this code as such:
```python
def fun(a):
    """
 Do something.

      :param a: do something with a
        """
```

I'm now going to step through execution of the function to see if I can find the issue, but I may not be adept enough at elisp to debug it myself.

**Comment by shabble** [comment]
I _think_ the problem might be related to the change described [here](https://github.com/emacs-mirror/emacs/commit/3bc7234349185da21828e5a2a1e31a16dcf93ba8#diff-f808b0589744f83f41d9f581e8b07001145598d2a2aa07fd40c1d20ee35df762) [(this actual change)](https://github.com/emacs-mirror/emacs/commit/0646c6817139aa905a2f6079fdc82eb4be944de0#diff-f808b0589744f83f41d9f581e8b07001145598d2a2aa07fd40c1d20ee35df762) and so the offsets that `python-docstring-fill` uses are now slightly off.

Very hacky patch because I'm too lazy to fix my github auth problems and push to a fork:

```diff
diff --git a/python-docstring.el b/python-docstring.el
index de9781e..ff5fa30 100644
--- a/python-docstring.el
+++ b/python-docstring.el
@@ -61,7 +61,7 @@ single space is used."
                                       (setf fill-it-anyway t)
                                       (throw 'not-a-string nil))))
                        (string-start (+ (goto-char (nth 8 syx))
-                                        3))
+                                        1))
                        (rawchar (if (eql (char-before (point)) ?r)
                                     1
                                   0))
@@ -75,7 +75,7 @@ single space is used."
                                (progn (forward-sexp)
                                       (point))
                              (error (point-max)))
-                           3))
+                           1))
                        (orig-offset (- orig-point string-start)))
                   (let*
                       ((offset-within
```

Seems to work for me. A proper fix probably needs to check the version of python.el and set offsets appropriately rather than just blindly overwriting them, or possibly could check that `(- string-start 1)` is actually the quote as expected, or something?

**Comment by timlod** [comment]
Appears to work for me, too - thanks! I will patch this for myself for now and see if it would run into any issues.

**Comment by vale981** [comment]
created a pr

**Comment by avatar-lavventura** [comment]
@vale981 Is the `PR` approved?

**Comment by vale981** [comment]
not yet :{

**Comment by glyph** [comment]
Sorry, I get a lot of github spam and things often fall through the cracks.

**Comment by glyph** [comment]
After installing from Elpa I can see the error quite clearly, thanks for the example.
